version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/data/postgres
    volumes:
      - data:/data/postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=db:5432
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"

volumes:
  data: